### ISSUE TITLE
Comma Ignored in Currency Conversion

### ISSUE THREAD

**Issue by Gasased** [Advaith3600/PowerToys-Run-Currency-Converter#15]
When entering a currency amount with a comma (e.g., $35,00 USD), the conversion tool ignores the comma, leading to incorrect results.

![image](https://github.com/user-attachments/assets/c1710f0b-5d97-4af9-884f-59567f35a793)
![image](https://github.com/user-attachments/assets/dbdafc6f-8316-4986-b964-d884fb75537e)

windows 11 Version 23H2 (OS Build 22631.3527)
sys language: eng, installation lang: ukrainian

**Comment by Advaith3600** [comment]
I will look into this as soon as possible. Why was the second expression deemed invalid? Is it still showing the same issue?

**Comment by idanyas** [comment]
encountered the same problem

comma ignored:
![PowerToys PowerLauncher_hDCVXF1sqb](https://github.com/user-attachments/assets/7482ab48-b1f0-4361-b8cb-8c72e1d74a9e)

dot invalid expression:
![PowerToys PowerLauncher_Lj6BXhNaaB](https://github.com/user-attachments/assets/3f1525ec-c97b-4ad3-b4d5-0dde2d3f6fb6)

**Comment by idanyas** [comment]
hello, any updates?

**Comment by Advaith3600** [comment]
Hey, I was quite busy the past few days. I will start working on a fix this week. Meantime, I am open to any contributions.

**Comment by Advaith3600** [comment]
I have made some changes, please let me know if this has fixed your issue.

[CurrencyConverter-1.1.5-ARM64.zip](https://github.com/user-attachments/files/16634600/CurrencyConverter-1.1.5-ARM64.zip)
[CurrencyConverter-1.1.5-x64.zip](https://github.com/user-attachments/files/16634603/CurrencyConverter-1.1.5-x64.zip)

**Comment by idmsln** [comment]
I downloaded the source, ran the build.ps1 file to build version 1.1.6. It worked fine for me. Thank you @Advaith3600 

![image](https://github.com/user-attachments/assets/820d3a85-7da6-4a41-8020-5c12eec534b9)

**Comment by Advaith3600** [comment]
Thanks for the feedback. I have published a stable build under [v1.1.6](https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/releases/tag/v1.1.6)

**Comment by idanyas** [comment]
i’ve noticed that converter handles numbers with commas as decimal separators really well, but when entering numbers with a dot as the separator, it seems to ignore it and treats the input as a whole number.

for example, if i type “0.001 btc,” it returns the conversion rate for “1 btc” instead of the smaller amount. i was wondering if there might be a way to modify this myself or if adding support for both comma and dot decimal separators could be considered.
![dot screenshot](https://github.com/user-attachments/assets/e45338ed-b898-47c6-a83a-01f9c9f4c259)

the comma works properly, though:
![comma screenshot](https://github.com/user-attachments/assets/10723910-124c-4f34-8382-814614dccd65)

**Comment by Advaith3600** [comment]
One obvious way to fix this is to change the system language, but it is not feasible for many. The plugin currently relies on the windows parseInt to determine the separator automatically, I need to check if there is a manual switch and how we can integrate it with the settings. Can you create a new issue about this?
